/*
 * Copyright (c) 2016 United States Government as represented by the Administrator of the
 * National Aeronautics and Space Administration. All Rights Reserved.
 */

package gov.nasa.worldwind.render;

import android.graphics.Bitmap;
import android.support.annotation.DrawableRes;

import gov.nasa.worldwind.util.Logger;
import gov.nasa.worldwind.util.WWUtil;

/**
 * Provides a mechanism for specifying images from a variety of sources. ImageSource retains the image source and its
 * associated type on behalf of the caller, making this information available to World Wind components that load images
 * on the caller's behalf.
 * <p/>
 * ImageSource supports four common source types used on the Android platform: <ul> <li>Android {@link
 * android.graphics.Bitmap}</li> <li>Android resource identifier</li> <li>File path</li> <li>Uniform Resource Locator
 * (URL)</li> </ul>
 * <p/>
 * ImageSource instances are intended to be used as a key into a cache or other data structure that enables sharing of
 * loaded images. Android resource identifiers with equivalent IDs are considered equivalent, as are file paths and URLs
 * with the same string representation. However, a Bitmap image source instance is considered unique, and is therefore
 * only equivalent to itself.
 */
public class ImageSource {

    protected static final int TYPE_BITMAP = 1;

    protected static final int TYPE_RESOURCE = 2;

    protected static final int TYPE_FILE_PATH = 3;

    protected static final int TYPE_URL = 4;

    protected static final int TYPE_UNKNOWN = 5;

    protected static long bitmapKeyPool = 0;

    protected Object source;

    protected Object key;

    protected int type;

    protected ImageSource() {
    }

    /**
     * Constructs an image source with a Bitmap. The Bitmap's dimensions should be no greater than 2048 x 2048.
     *
     * @param bitmap the bitmap to use as an image source
     *
     * @return the new image source
     *
     * @throws IllegalArgumentException If the bitmap is null or recycled
     */
    public static ImageSource fromBitmap(Bitmap bitmap) {
        if (bitmap == null || bitmap.isRecycled()) {
            throw new IllegalArgumentException(
                Logger.logMessage(Logger.ERROR, "ImageSource", "fromBitmap", "invalidBitmap"));
        }

        ImageSource imageSource = new ImageSource();
        imageSource.source = bitmap;
        imageSource.key = nextBitmapKey();
        imageSource.type = TYPE_BITMAP;

        return imageSource;
    }

    /**
     * Constructs an image source with an Android resource identifier. The resource must be accessible from the Android
     * Context associated with the World Window, and its dimensions should be no greater than 2048 x 2048.
     *
     * @param id the resource identifier, as generated by the aapt tool
     *
     * @return the new image source
     */
    public static ImageSource fromResource(@DrawableRes int id) {
        ImageSource imageSource = new ImageSource();
        imageSource.source = id;
        imageSource.key = id;
        imageSource.type = TYPE_RESOURCE;

        return imageSource;
    }

    /**
     * Constructs an image source with a file path.
     *
     * @param pathName complete path name to the file
     *
     * @return the new image source
     *
     * @throws IllegalArgumentException If the path name is null
     */
    public static ImageSource fromFilePath(String pathName) {
        if (pathName == null) {
            throw new IllegalArgumentException(
                Logger.logMessage(Logger.ERROR, "ImageSource", "fromFilePath", "missingPathName"));
        }

        ImageSource imageSource = new ImageSource();
        imageSource.source = pathName;
        imageSource.key = pathName;
        imageSource.type = TYPE_FILE_PATH;

        return imageSource;
    }

    /**
     * Constructs an image source with a URL string. The image's dimensions should be no greater than 2048 x 2048. The
     * application's manifest must include the permissions that allow network connections.
     *
     * @param urlString complete URL string
     *
     * @return the new image source
     *
     * @throws IllegalArgumentException If the URL string is null
     */
    public static ImageSource fromUrl(String urlString) {
        if (urlString == null) {
            throw new IllegalArgumentException(
                Logger.logMessage(Logger.ERROR, "ImageSource", "fromUrl", "missingUrl"));
        }

        ImageSource imageSource = new ImageSource();
        imageSource.source = urlString;
        imageSource.key = urlString;
        imageSource.type = TYPE_URL;

        return imageSource;
    }

    /**
     * Constructs an image source with a generic Object instance. The source may be any non-null Object. This is
     * equivalent to calling one of ImageSource's type-specific factory methods when the source is a recognized type:
     * Bitmap; integer resource ID; file path; URL string.
     *
     * @param source the generic source
     *
     * @return the new image source
     *
     * @throws IllegalArgumentException If the source is null
     */
    public static ImageSource fromObject(Object source) {
        if (source == null) {
            throw new IllegalArgumentException(
                Logger.logMessage(Logger.ERROR, "ImageSource", "fromObject", "missingSource"));
        }

        if (source instanceof Bitmap) {
            return fromBitmap((Bitmap) source);
        } else if (source instanceof Integer) { // Android resource identifier, as generated by the aapt tool
            return fromResource((Integer) source);
        } else if (source instanceof String && WWUtil.isUrlString((String) source)) {
            return fromUrl((String) source);
        } else if (source instanceof String) {
            return fromFilePath((String) source);
        } else {
            ImageSource imageSource = new ImageSource();
            imageSource.source = source;
            imageSource.key = source;
            imageSource.type = TYPE_UNKNOWN;
            return imageSource;
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || this.getClass() != o.getClass()) {
            return false;
        }

        ImageSource that = (ImageSource) o;
        return this.key.equals(that.key) && this.type == that.type;
    }

    @Override
    public int hashCode() {
        return 31 * this.key.hashCode() + this.type;
    }

    @Override
    public String toString() {
        return this.source.toString();
    }

    /**
     * Indicates whether this image source is a Bitmap.
     *
     * @return true if the source is a Bitmap, otherwise false
     */
    public boolean isBitmap() {
        return this.type == TYPE_BITMAP;
    }

    /**
     * Indicates whether this image source is an Android resource.
     *
     * @return true if the source is an Android resource, otherwise false
     */
    public boolean isResource() {
        return this.type == TYPE_RESOURCE;
    }

    /**
     * Indicates whether this image source is a file path.
     *
     * @return true if the source is an file path, otherwise false
     */
    public boolean isFilePath() {
        return this.type == TYPE_FILE_PATH;
    }

    /**
     * Indicates whether this image source is a URL string.
     *
     * @return true if the source is a URL string, otherwise false
     */
    public boolean isUrl() {
        return this.type == TYPE_URL;
    }

    /**
     * Returns the source Bitmap. Call isBitmap to determine whether or not the source is a Bitmap.
     *
     * @return the Bitmap, or null if the source is not a Bitmap
     */
    public Bitmap asBitmap() {
        return (this.type == TYPE_BITMAP) ? (Bitmap) this.source : null;
    }

    /**
     * Returns the source Android resource identifier. Call isResource to determine whether or not the source is an
     * Android resource.
     *
     * @return the resource identifier as generated by the aapt tool, or null if the source is not an Android resource
     */
    @DrawableRes
    public int asResource() {
        return (this.type == TYPE_RESOURCE) ? (int) this.source : 0;
    }

    /**
     * Returns the source file path name. Call isFilePath to determine whether or not the source is a file path.
     *
     * @return the file path name, or null if the source is not a file path
     */
    public String asFilePath() {
        return (this.type == TYPE_FILE_PATH) ? (String) this.source : null;
    }

    /**
     * Returns the source URL string. Call isUrl to determine whether or not the source is a URL string.
     *
     * @return the URL string, or null if the source is not a URL string
     */
    public String asUrl() {
        return (this.type == TYPE_URL) ? (String) this.source : null;
    }

    /**
     * Returns the image source as a generic Object instance.
     *
     * @return the source object
     */
    public Object asObject() {
        return this.source;
    }

    protected static String nextBitmapKey() {
        return "ImageSource " + (++bitmapKeyPool);
    }
}
