/*
 * Copyright (c) 2016 United States Government as represented by the Administrator of the
 * National Aeronautics and Space Administration. All Rights Reserved.
 */

package gov.nasa.worldwind.layer;

import android.support.annotation.DrawableRes;

import gov.nasa.worldwind.R;
import gov.nasa.worldwind.geom.Sector;
import gov.nasa.worldwind.shape.SurfaceImage;
import gov.nasa.worldwind.util.Logger;

/**
 * Displays NASA's Blue Marble next generation imagery from an Android drawable resource. By default,
 * BlueMarbleBackgroundLayer is configured to retrieve the 40km resolution image from the built-in World Wind library
 * resource res/drawable/gov_nasa_worldwind_worldtopobathy2004053.
 * <p/>
 * Information on NASA's Blue Marble next generation imagery can be found at http://earthobservatory.nasa.gov/Features/BlueMarble/
 */
public class BlueMarbleBackgroundLayer extends RenderableLayer { // TODO rename as BackgroundLayer, adjust comments

    /**
     * Constructs a Blue Marble image layer with the built-in World Wind library resource
     * res/drawable/gov_nasa_worldwind_worldtopobathy2004053. The resource must be accessible from the Android Context
     * associated with the World Window.
     */
    public BlueMarbleBackgroundLayer() {
        this.initWithImageSource(R.drawable.gov_nasa_worldwind_worldtopobathy2004053);
    }

    /**
     * Constructs a Blue Marble image layer with a specified drawable resource. The image's dimensions must be no
     * greater than 2048 x 2048. The resource must be accessible from the Android Context associated with the World
     * Window.
     *
     * @param resourceId the resource identifier, as generated by the aapt tool
     */
    public BlueMarbleBackgroundLayer(@DrawableRes int resourceId) {
        this.initWithImageSource(resourceId);
    }

    /**
     * Constructs a Blue Marble image layer with a specified image URL. The image's dimensions must be no greater than
     * 2048 x 2048. The application's manifest must include the permissions that allow network connections.
     *
     * @param urlString string indicating the image URL
     *
     * @throws IllegalArgumentException If the URL is null
     */
    public BlueMarbleBackgroundLayer(String urlString) {
        if (urlString == null) {
            throw new IllegalArgumentException(
                Logger.logMessage(Logger.ERROR, "BlueMarbleBackgroundLayer", "constructor", "missingUrl"));
        }

        this.initWithImageSource(urlString);
    }

    protected void initWithImageSource(Object imageSource) {
        this.setDisplayName("Blue Marble Background");

        // Disable picking for the layer because it covers the full sphere and will override a terrain pick.
        this.setPickEnabled(false);

        // Delegate display to the SurfaceImage shape.
        this.addRenderable(new SurfaceImage(new Sector().setFullSphere(), imageSource));
    }
}
