/*
 * Copyright (c) 2016 United States Government as represented by the Administrator of the
 * National Aeronautics and Space Administration. All Rights Reserved.
 */

package gov.nasa.worldwind.layer;

import android.support.annotation.DrawableRes;

import gov.nasa.worldwind.R;
import gov.nasa.worldwind.geom.Sector;
import gov.nasa.worldwind.shape.SurfaceImage;

/**
 * Displays NASA's Blue Marble next generation imagery from an Android drawable resource. By default,
 * BlueMarbleBackgroundLayer is configured to retrieve the 3 pixels/degree resolution image at resource
 * res/drawable/gov_nasa_worldwind_worldtopobathy2004053.
 * <p/>
 * Information on NASA's Blue Marble next generation imagery can be found at http://earthobservatory.nasa.gov/Features/BlueMarble/
 */
public class BlueMarbleBackgroundLayer extends RenderableLayer {

    /**
     * Constructs a Blue Marble image layer with image at res/drawable/gov_nasa_worldwind_worldtopobathy2004053.
     */
    public BlueMarbleBackgroundLayer() {
        this(R.drawable.gov_nasa_worldwind_worldtopobathy2004053);
    }

    /**
     * Constructs a Blue Marble image layer with a specified drawable resource. The resource's dimensions must be no
     * greater than 2048 x 2048.
     *
     * @param resourceId the resource identifier, as generated by the aapt tool
     */
    public BlueMarbleBackgroundLayer(@DrawableRes int resourceId) {
        super("Blue Marble Background");

        // Delegate display to the SurfaceImage shape.
        this.addRenderable(new SurfaceImage(new Sector().setFullSphere(), resourceId));

        // Disable picking for the layer because it covers the full sphere and will override a terrain pick.
        this.setPickEnabled(false);
    }
}
